### ISSUE TITLE
No DynamoDB Update Stream Triggers found routing to LambdaStreamToFirehose

### ISSUE THREAD

**Issue by BMR59920** [awslabs/dynamodb-continuous-backup#11]
Provisioned tables using provision_tables.py are not de-provisioned using deprovision_tables.py

11/07 12:03 > ./deprovision_tables.py provisioning_whitelist.hjson
Building Table List for Processing from provisioning_whitelist.hjson
Loaded configuration from config.hjson
Removed Event Source Mapping for DynamoDB Update Stream arn:aws:dynamodb:us-west-2:$ACCOUNT:table/bobStackLocal-DynamoDBLocalCMV1-1TBKHYKVQ0YS8-configurationSpec-YUVCHLSWS637/stream/2016-11-03T16:00:07.347
No DynamoDB Update Stream Triggers found routing to LambdaStreamToFirehose for bobStackLocal-DynamoDBLocalCMV1-1TBKHYKVQ0YS8-configurationSpec-YUVCHLSWS637 - OK

Also : This does not remove the firehose entries.

**Comment by IanMeyers** [comment]
When you say 'firehose entries', do you mean that the firehose delivery stream is not being deleted? Is there any more log information you can share?

**Comment by BMR59920** [comment]
Correct. Although this seems to be related to the table names longer than 64 characters.

I have tested with table names less than 64 characters and it functions properly.

**Comment by IanMeyers** [comment]
Yep - this should be fixed with the latest version.

**Comment by BMR59920** [comment]
Re-tested with names longer than 64 characters, and while the firehose stream name and S3 Delivery Streams name field show truncated names, the CloudWatch logs suggest that this name length issue is still present.

DynamoDB: pdhStackLocal-DynamoDBLocalMMV1-ZU4C23KH1A0V-dataUnit-1QDO1X8MYWMPA
arn:aws:dynamodb:us-west-2:$ACCOUNT:table/bobStackLocal-DynamoDBLocalMMV1-ZU4C23KH1A0V-dataUnit-1QDO1X8MYWMPA/stream/2016-08-23T21:42:37.147
Batch size: 1000Last result: PROBLEM: Function call failed

18:45:22  2016-11-09T18:45:22.992Z  f4c318cb-d1fa-41e1-9ad5-d2a8c1d41d72    Writing to firehose
18:45:23  2016-11-09T18:45:23.212Z  f4c318cb-d1fa-41e1-9ad5-d2a8c1d41d72    {"message":"1 validation error detected: Value 'bobStackLocal-DynamoDBLocalMMV1-ZU4C23KH1A0V-dataUnit-1QDO1X8MYWMPA ' at 'deliveryStreamName' failed to satisfy constraint: Member must have length less than or equal to 64","code":"ValidationException","time":"2016-11-09T18:45:23.212Z","requestId":"abfba4cc-a6ac-11e6-b497-0d080bc63d70","s
18:45:23  2016-11-09T18:45:23.213Z  f4c318cb-d1fa-41e1-9ad5-d2a8c1d41d72    Forwarding failure after 0 successful batches
18:45:23  2016-11-09T18:45:23.213Z  f4c318cb-d1fa-41e1-9ad5-d2a8c1d41d72    Processing Complete
18:45:23  2016-11-09T18:45:23.213Z  f4c318cb-d1fa-41e1-9ad5-d2a8c1d41d72    {"errorMessage":"ERROR"}

Not sure if this is related, but, the LambdaStreamToFirehose trigger names are still the same length as the table names.

**Comment by IanMeyers** [comment]
1.3.5 has now been patched with the delivery stream length restriction

**Comment by BMR59920** [comment]
This appears to be fixed. Thank you!
